// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yeuxhwedklxdommvbnoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlldXhod2Vka2x4ZG9tbXZibm96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NzE4MTEsImV4cCI6MjA2NzA0NzgxMX0.OqAW96wc2v4XnAkPv7hantQxKAiGYJuwAXAqk_EoiPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});